/*
* 常亮模块
* */

export const SAVE_USER="SAVE_USER";
export const REMOVE_USER="REMOVE_USER";
export const SET_TITLE="SET_TITLE";
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS";
export const ADD_CATEGORY_SUCCESS="ADD_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_SUCCESS="UPDATE_CATEGORY_SUCCESS";
export const GET_ROLE_SUCCESS="GET_ROLE_SUCCESS"
export const ADD_ROLE_SSUCCESS="ADD_ROLE_SSUCCESS"
export const UPDATE_ROLES_SUCCESS="UPDATE_ROLES_SUCCESS"